---
- name: download zabbix-agent repo
  shell: "wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb"
- name: dpkg zabbix-agent
  shell: "dpkg -i zabbix-release_3.2-1+xenial_all.deb"
- name: install zabbix-agent
  apt:
    name: zabbix-agent
    update_cache: yes

- name: copy config
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  notify:
     - restart zabbix-agent
